### ISSUE TITLE
vcpkg安装后使用cmake find_package(co) 找不到库

### ISSUE THREAD

**Issue by xbyl1234** [idealvin/cocoyaxi#183]

**Comment by idealvin** [comment]
- 需要写一个 .cmake 文件，我暂时没空弄，可以参考这个：https://github.com/microsoft/vcpkg/blob/master/ports/curl/vcpkg-cmake-wrapper.cmake，给 co 写一个 .cmake。
- vcpkg 安装的那个版本在 windows 上有个 bug，会影响在协程中使用三方网络库，目前最好直接用 master 最新代码。

**Comment by xbyl1234** [comment]
给大佬点赞

**Comment by xq114** [comment]
xmake可以自动生成.cmake文件 https://xmake.io/#/zh-cn/manual/custom_rule?id=utilsinstallcmake_importfiles

**Comment by idealvin** [comment]
> xmake可以自动生成.cmake文件 https://xmake.io/#/zh-cn/manual/custom_rule?id=utilsinstallcmake_importfiles

这个怎么用呢？跟 [libcurl](https://github.com/microsoft/vcpkg/blob/master/ports/curl/vcpkg-cmake-wrapper.cmake) 这个是同类型的吗？

**Comment by xq114** [comment]
在xmake.lua中加一行
```
add_rules("utils.install.cmake_importfiles")
```
就可以了，之后假设安装到`<PREFIX>`，运行`xmake install -o <PREFIX>`就可以生成

https://github.com/xq114/SuiteSparse-xmake/blob/main/xmake.lua 这是一个例子

cmake要引用也很简单，
```
export CMAKE_PREFIX_PATH=<PREFIX>:$CMAKE_PREFIX_PATH
cmake <path-to-user-project>
```
位于`<path-to-user-project>`里面的`find_package(co)`就可以找到，之后`target_link_libraries(main co::libco)`就行

要和vcpkg结合的话，需要先xmake install一遍然后把生成的lib/cmake/co/*.cmake提取出来加入项目（假设放在cmake文件夹下），然后在cmake的install里面加一行copy这些文件到目标文件夹
```
install(FILES cmake/*.cmake DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/co)
```

**Comment by idealvin** [comment]
@xq114 

感谢反馈，我试试。

https://www.zhihu.com/people/vin.cc
可以去上面给我发条消息，我拉到群里..

**Comment by idealvin** [comment]
fixed by @SpaceIm in #206
