### ISSUE TITLE
有DLL版本吗

### ISSUE THREAD

**Issue by 1027663760** [idealvin/cocoyaxi#199]
我这边改编译成DLL版本供其它语言调用太麻烦了，下载到源代码没办法直接用vs编译，缺了很多文件与参数...每次都得折腾半天

**Comment by idealvin** [comment]
建议用 xmake 编译，动态库的编译可以参考[这里](https://idealvin.gitee.io/cn/co/build/#%E7%BC%96%E8%AF%91%E5%8A%A8%E6%80%81%E5%BA%93)

**Comment by 1027663760** [comment]
> 建议用 xmake 编译，动态库的编译可以参考[这里](https://idealvin.gitee.io/cn/co/build/#%E7%BC%96%E8%AF%91%E5%8A%A8%E6%80%81%E5%BA%93)

我不太会用这个xmake。。。

**Comment by 1027663760** [comment]
而且我是用于windows平台的...

**Comment by idealvin** [comment]
你不需要会用，安装xmake，照着执行那两条命令就好了

**Comment by 1027663760** [comment]
> > 我不太会用这个xmake。。。
> 
> 你不需要会用，安装xmake，照着执行那两条命令就好了

好吧，我再试试，之前安装后执行那两条命令不成功
