### ISSUE TITLE
gcc link failed

### ISSUE THREAD

**Issue by jaueone** [idealvin/cocoyaxi#200]
/usr/bin/ld: /home/public/workSpaces/MY_UNTOUCH_ROOT/externals/co/lib/libco.a(hook.cc.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by jaueone** [comment]
上面添加 dl　库好了，又有一个新的问题

**Comment by jaueone** [comment]
libopencv_core.so.3.4.15  -lpthread && :
/home/public/workSpaces/MY_UNTOUCH_ROOT/externals/co/lib/libco.a(stack_trace.cc.o): In function `co::StackTraceImpl::dump_stack(void*, int)':
/home/public/workSpaces/co/src/log/stack_trace.cc:125: undefined reference to `backtrace_create_state'
/home/public/workSpaces/co/src/log/stack_trace.cc:126: undefined reference to `backtrace_full'
collect2: error: ld returned 1 exit status

**Comment by idealvin** [comment]
> libopencv_core.so.3.4.15 -lpthread && : /home/public/workSpaces/MY_UNTOUCH_ROOT/externals/co/lib/libco.a(stack_trace.cc.o): In function `co::StackTraceImpl::dump_stack(void*, int)': /home/public/workSpaces/co/src/log/stack_trace.cc:125: undefined reference to `backtrace_create_state' /home/public/workSpaces/co/src/log/stack_trace.cc:126: undefined reference to `backtrace_full' collect2: error: ld returned 1 exit status

链接 backtrace 库就可以了

**Comment by jaueone** [comment]
> > libopencv_core.so.3.4.15 -lpthread && : /home/public/workSpaces/MY_UNTOUCH_ROOT/externals/co/lib/libco.a(stack_trace.cc.o): In function `co::StackTraceImpl::dump_stack(void*, int)': /home/public/workSpaces/co/src/log/stack_trace.cc:125: undefined reference to `backtrace_create_state' /home/public/workSpaces/co/src/log/stack_trace.cc:126: undefined reference to `backtrace_full' collect2: error: ld returned 1 exit status
> 
> 链接 backtrace 库就可以了

ok，解决了

**Comment by youngday** [comment]
if we  could add libbacktrace in this project , or, we need add it manully .
in conanfile  ,add  "libbacktrace/cci.20210118",  
in cmakelists.txt  ,add target_link_libraries(backtrace)
