### ISSUE TITLE
attempt to call global 'on_fetch' (a nil value) 

### ISSUE THREAD

**Issue by sunnyboy00** [idealvin/cocoyaxi#205]
deepin 20.3 

xmake f --with_libcurl=true --with_openssl=true

 checking for architecture ... x86_64 
checking for libbacktrace ... ok 
checking for cxxabi ... ok

 error: ...ake/repositories/xmake-repo/packages/o/openssl/xmake.lua:16: attempt to call global 'on_fetch' (a nil value) 
stack traceback:     [...ake/repositories/xmake-repo/packages/o/openssl/xmake.lua:16]: in main chunk

**Comment by idealvin** [comment]
xmake f -vD --with_libcurl=true --with_openssl=true
看看详细的报错信息

**Comment by sunnyboy00** [comment]
xmake f -vD --with_libcurl=true --with_openssl=true

checking for architecture ... x86_64
checking for gcc ... /usr/bin/gcc
checkinfo: cannot runv(dmd --version), No such file or directory
checking for dmd ... no
checkinfo: cannot runv(ldc2 --version), No such file or directory
checking for ldc2 ... no
checkinfo: cannot runv(gdc --version), No such file or directory
checking for gdc ... no
checking for gcc ... /usr/bin/gcc
checking for the c compiler (cc) ... gcc
checking for the c++ compiler (cxx) ... gcc
checking for ccache ... /usr/bin/ccache
> /usr/bin/ccache /usr/bin/gcc -c -m64 -o /dev/shm/.xmake1000/220110/_144D98BE51D2490080C82F58BF42F120.o /dev/shm/.xmake1000/220110/_B10CA37A2F2E4D108E08F20E2B0A7730.c
> /usr/bin/ccache /usr/bin/gcc -c -m64 -o /dev/shm/.xmake1000/220110/_E106D85164F74F00810F839D65F4EC40.o /dev/shm/.xmake1000/220110/_3E216EFE8EFA47008D4FE37C54750800.cpp
checking for /usr/bin/gcc ... ok
checking for flags (-fdiagnostics-color=always) ... ok
> gcc "-fdiagnostics-color=always" "-m64"
checking for flags (-fdiagnostics-color=always) ... ok
> gcc "-fdiagnostics-color=always"
> checking for c includes(backtrace.h)
checking for libbacktrace ... ok
> checking for c++ includes(cxxabi.h)
checking for cxxabi ... ok
checking for unzip ... /usr/bin/unzip
checking for git ... /usr/bin/git
checking for gzip ... /usr/bin/gzip
checking for tar ... /usr/bin/tar
checking for ping ... /usr/bin/ping
pinging for the host(gitlab.com) ... 198 ms
pinging for the host(gitee.com) ... 37 ms
checkinfo: cannot runv(nmap --version), No such file or directory
checking for nmap ... no
pinging for the host(github.com) ... 65535 ms
error: @programdir/core/main.lua:290: ...dir/core/sandbox/modules/import/core/package/package.lua:76: ...ake/repositories/xmake-repo/packages/o/openssl/xmake.lua:16: attempt to call global 'on_fetch' (a nil value)
stack traceback:
    [...ake/repositories/xmake-repo/packages/o/openssl/xmake.lua:16]: in main chunk

stack traceback:
        [C]: in function 'error'
        @programdir/core/base/os.lua:787: in function 'raise'
        @programdir/core/main.lua:290: in function 'cotask'
        @programdir/core/base/scheduler.lua:317: in function <@programdir/core/base/scheduler.lua:315>

**Comment by idealvin** [comment]
更新 xmake 版本试试

**Comment by sunnyboy00** [comment]
xmake update 之后OK
