### ISSUE TITLE
ue项目中尝试编译报了一堆错

### ISSUE THREAD

**Issue by ActivePeter** [idealvin/cocoyaxi#214]
![image](https://user-images.githubusercontent.com/8100696/152014771-995a694d-1c0d-4db3-8d80-a9821b0fc71a.png)

**Comment by idealvin** [comment]
- 编译器需要支持 C++11
- 在 windows 上，定义 WIN32_LEAN_AND_MEAN 试试

**Comment by ActivePeter** [comment]
![image](https://user-images.githubusercontent.com/8100696/152107986-26c84dee-cef4-45a3-bc0c-0934397b30a3.png)
解决了，是ue引入第三方库需要加上这个宏
