### ISSUE TITLE
多链接库的协程分配疑问

### ISSUE THREAD

**Issue by hoskylucky** [idealvin/cocoyaxi#225]
作者您好，我最近在学习这个牛逼库，我有个疑问就是一个进程包含多个链接库，按照您之前的建议是每个链接库都需要静态链接libco，那是否意味着每个链接库都会分配独立的一套调度线程，如果他们互相交互的话是否还是要使用线程锁？另外多链接库中，多静态全局变量在win/linux下是否可以表现一致？因为我之前遇到过这样的问题。谢谢。

**Comment by idealvin** [comment]
> 作者您好，我最近在学习这个牛逼库，我有个疑问就是一个进程包含多个链接库，按照您之前的建议是每个链接库都需要静态链接libco，那是否意味着每个链接库都会分配独立的一套调度线程，如果他们互相交互的话是否还是要使用线程锁？另外多链接库中，多静态全局变量在win/linux下是否可以表现一致？因为我之前遇到过这样的问题。谢谢。

- 不同线程间的交互，需要一些同步机制
- co 现在支持动态库，可以试试动态库
