### ISSUE TITLE
未来会增加并发集合类吗，类似于java的concurrent包里

### ISSUE THREAD

**Issue by touwaeriol** [idealvin/cocoyaxi#226]
希望能增加并发集合类，自己写的话手动上锁有些麻烦

**Comment by idealvin** [comment]
> 希望能增加并发集合类，自己写的话手动上锁有些麻烦

能给个简单的用法示例吗？

**Comment by touwaeriol** [comment]
能协程里面使用的线程安全的集合类，Vector，List，Map等的并发安全实现。现在在协程里面使用集合类只能手动加锁吧？

**Comment by touwaeriol** [comment]
另外我想知道如果我在多个协程里面使用Vector，使用co提供的Mutex能保证并发安全吗

**Comment by idealvin** [comment]
> 另外我想知道如果我在多个协程里面使用Vector，使用co提供的Mutex能保证并发安全吗

可以，直接在 STL 上面套一层 co::Mutex

**Comment by touwaeriol** [comment]
> > 另外我想知道如果我在多个协程里面使用Vector，使用co提供的Mutex能保证并发安全吗
> 
> 可以，直接在 STL 上面套一层 co::Mutex

>>

> > 另外我想知道如果我在多个协程里面使用Vector，使用co提供的Mutex能保证并发安全吗
> 
> 可以，直接在 STL 上面套一层 co::Mutex

**Comment by touwaeriol** [comment]
好的，我先就这样来实现吧。希望未来co能提供这些类

**Comment by mankouzhuya** [comment]
同上，希望作者加上一些协程安全的容器实现。比如搞个util类，可以直接创建协程安全的容器。或者提供一个装饰器函数，把输入的普通容器装饰为协程安全的容器。
