### ISSUE TITLE
tcpserver如何发送从其他线程来的数据？

### ISSUE THREAD

**Issue by squirrelfish** [idealvin/cocoyaxi#227]

**Comment by idealvin** [comment]
tcp::Server 基于协程实现，采用同步的编程方式，可以参考[这里](https://cocoyaxi.gitee.io/cn/co/coroutine/#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E7%BD%91%E7%BB%9C%E6%A8%A1%E5%9E%8B)。

要发送其他线程的数据，采用 协程同步机制 (co::Event, co::WaitGroup，co::Chan等) 就可以了。
