### ISSUE TITLE
有性能数据吗？4K的socket echo server，能打到多少Gbps的带宽？

### ISSUE THREAD

**Issue by beef9999** [idealvin/cocoyaxi#231]

**Comment by idealvin** [comment]
> _No description provided._

你可以拿个万兆网卡试试

**Comment by beef9999** [comment]
。。。
那有磁盘IO数据吗？NVMe SSD能打到多少QPS？

**Comment by idealvin** [comment]
> 。。。 那有磁盘IO数据吗？NVMe SSD能打到多少QPS？

之前测过 co/rpc，简单的发送小数据，单线程 QPS 可以达到 12-13 万

**Comment by beef9999** [comment]
有点低，10Gb网卡是吧

**Comment by idealvin** [comment]
> 有点低，10Gb网卡是吧

注意是单线程的，这个已经是极限性能了。网卡远远没跑满..

**Comment by beef9999** [comment]
网卡带宽上去之后，通信延时也会变小，所以数据会好一点。
我们能到50万

**Comment by idealvin** [comment]
> 网卡带宽上去之后，通信延时也会变小，所以数据会好一点。 我们能到50万

你们走的标准的 TCP/IP 协议栈吗？

**Comment by idealvin** [comment]
那可以用 co 的代码，在你们的环境测一下

**Comment by beef9999** [comment]
是标准tcp
能给我发个二进制吗 我还不会跑你的程序

beef9999#qq.com

**Comment by idealvin** [comment]
> 网卡带宽上去之后，通信延时也会变小，所以数据会好一点。 我们能到50万 而且是send/recv的echo server

我测的是 co/rpc 框架，与简单的 echo 可能还不一样

**Comment by idealvin** [comment]
> 是标准tcp 能给我发个二进制吗 我还不会跑你的程序
> 
> beef9999#qq.com

我不知道你是哪个平台做测试，不过你可以下载 co master 代码，安装 xmake ，
```bash
cd co
xmake -b rpc
xmake r rpc
```
像上面就可以启动测试程序中的 rpc server

**Comment by beef9999** [comment]
这没法跑吧。。
至少得有个client，以及设置目标IP， buffer size参数的功能吧

**Comment by beef9999** [comment]
感觉测网络性能echo server是标配。rpc的话，协议不一样就没法比较了

**Comment by idealvin** [comment]
> 感觉测网络性能echo server是标配。rpc的话，协议不一样就没法比较了

test/so 目录下有些网络测试程序，可以稍微改一下，可以看看 test/so/tcp.cc 能不能满足你的要求。在 co 根目录执行 `xmake -b tcp` 就可以编译该文件。

**Comment by idealvin** [comment]
我现在可以加一个 echo 的

**Comment by beef9999** [comment]
行吧。我下周有空格改改测测
你之前跟libco / libgo 这些比较过性能吗？

**Comment by beef9999** [comment]
> 

你要是能加那自然最好了

**Comment by idealvin** [comment]
你们的 echo 用的什么协议？有自己定义的头部？

**Comment by beef9999** [comment]
没有协议啊，裸socket发4K，收4K

**Comment by idealvin** [comment]
那可以，我这边可以设置个可调的参数

**Comment by beef9999** [comment]
https://github.com/haraldh/rust_echo_bench
https://github.com/haraldh/rust_echo_server
比如这个，虽然是其他语言的，但基本都是这样的参数

**Comment by idealvin** [comment]
> https://github.com/haraldh/rust_echo_bench https://github.com/haraldh/rust_echo_server 比如这个，虽然是其他语言的，但基本都是这样的参数
> 
> 这样任何语言的程序，都能混着测了。可以一起比较性能了

已经提交了 test/so/echo.cc，你可能要改一下：
```sh
xmake -b echo

# server
xmake r echo

# client:  -c 连接数，-n 发包数， -b 包大小
xmake r echo -c 100 -n 1000000 -b 4096
```

**Comment by beef9999** [comment]
程序有bug，跑不起来

**Comment by idealvin** [comment]
> 程序有bug，跑不起来

更新了下代码，与 rust bench 参数保持一致

**Comment by beef9999** [comment]
客户端起64个连接，可以打到50万QPS，但服务端CPU 350%

**Comment by beef9999** [comment]
我们的server能在CPU能在100%的情况下打到50万QPS

**Comment by idealvin** [comment]
> 客户端起64个连接，可以打到50万QPS，但服务端CPU 350%

echo server 端默认开启的线程数是 cpu 核数，可以用 -co_sched_num 指定服务端线程数量
```sh
xmake r echo -l 4096 -co_sched_num 8
```

**Comment by idealvin** [comment]
> 客户端起64个连接，可以打到50万QPS，但服务端CPU 350%

这个是把网卡打满了？

**Comment by beef9999** [comment]
没有，网卡40Gb

**Comment by beef9999** [comment]
CPU满了

**Comment by beef9999** [comment]
指定 co_sched_num = 1的话，21万QPS

**Comment by idealvin** [comment]
> 指定 co_sched_num = 1的话，21万QPS

这就是单线程的 qps

**Comment by beef9999** [comment]
单线程多协程的吧。你这个是有栈协程吗？怎么做的跨cpu调度的

**Comment by idealvin** [comment]
> 单线程多协程的吧。你这个是有栈协程吗？怎么做的跨cpu调度的

对的，一个连接一个协程

**Comment by idealvin** [comment]
co_sched_num 设置成 4，qps 能超过 50 万吗？

**Comment by beef9999** [comment]
因为你这个qps是显示在客户端的，但其实客户端可能是瓶颈，得多起几个客户端测比较好， qps每秒打印在服务端这种

**Comment by beef9999** [comment]
我客户端和服务端都设置了co_sched_num=4，可以到50万，服务端CPU 300%多

**Comment by idealvin** [comment]
rust_bench 就是在客户端显示的啊

**Comment by beef9999** [comment]
行吧，我只是说size ip port这些参数可以学它。

**Comment by idealvin** [comment]
你可以看看代码，自己改一下，应该比较方便的

**Comment by beef9999** [comment]
https://github.com/alibaba/PhotonLibOS 这是我们最近开源的项目

我们的协程虽然支持跨线程调用/唤醒/同步等，但其实是靠代码主动触发，一般尽量不跨线程。

看你的协程貌似是一种被动的调度到多线程？是咋做的？没有性能损失吗？

**Comment by idealvin** [comment]
> 

co 协程这部分与 golang 中的 goroutine 类似
