### ISSUE TITLE
socket为啥不加锁。。。

### ISSUE THREAD

**Issue by beef9999** [idealvin/cocoyaxi#233]
读锁 写锁
不加的话，就读写错误了吧

**Comment by idealvin** [comment]
tcp socket，支持一个协程读、一个协程写，不需要加锁

**Comment by beef9999** [comment]
根据manual手册，读的时候完全可能读部分就返回吧。如果这时候不加锁，别的协程就写了，如何保证数据正确性

**Comment by idealvin** [comment]
> 根据manual手册，读的时候完全可能读部分就返回吧。如果这时候不加锁，别的协程抢到机会就读了，如何保证数据正确性

socket 本来就不支持多个协程同时读，设计协程库没必要考虑这个问题
