### ISSUE TITLE
如何正确地使用此库的hook？

### ISSUE THREAD

**Issue by dragon-zhang** [idealvin/cocoyaxi#234]
```c++
#include "co/all.h"

int main(int argc, char** argv) {
    //argv传什么参数，会启用hook？
    flag::init(argc, argv);
    //后续的一切行为，是否都可以认为，会调用被hook的方法？
    //比如调用系统函数sleep，实际上调用的是hook后的函数？
    return 0;
}
```

**Comment by idealvin** [comment]
@dragon-zhang 
hook 默认已经启用，不需要通过 argv 控制。

**Comment by dragon-zhang** [comment]
感谢，我试试，如果没问题，我会关闭这个issue







------------------ 原始邮件 ------------------
发件人: Alvin ***@***.***&gt;
发送时间: 2022年6月26日 22:15
收件人: idealvin/cocoyaxi ***@***.***&gt;
抄送: dragon-zhang ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [idealvin/cocoyaxi] 如何正确地使用此库的hook？ (Issue #234)





 
@dragon-zhang
 hook 默认已经启用，不需要通过 argv 控制。
